### PR TITLE
Add more info, deny qrcode with psk

### PR DESCRIPTION
**Pull request by nobbes**
Sorry, I just optimized the output and tested with PSK and QR codes: not working with iOS 17, but works with Android 12. So it's denied.

### CODE REVIEW

**Comment by cablethief** [comment]
What does the USE_PSK check for please? (sorry its been a while since I made this)

**Comment by cablethief** [comment]
Just checked, I see. thats fine then

**Comment by cablethief** [comment]
The phrase cant be used with PSK is confusing. you should rather say "cant be used with EAP or 64 hex digit pre-shared-key" 
as WPA-PSK is the main point of this QR code and it can cause confusion.

**Comment by cablethief** [comment]
In the help doc just leave it as "(requires qrencode)" dont bother adding the no EAP thing there.

**Comment by nobbes** [comment]
Thanks for your support, should be ready now.

**Pull request merged**
